### ISSUE TITLE
Timeout error

### ISSUE THREAD

**Issue by hyiltiz** [nschloe/gitfaces#12]
It seems to time out. I ran a few times (on Spacemacs repo), and every time I re-ran, it managed to collect some more items in the repo. I just pip3 installed it (I'd give version number for gitfaces but it doesn't report anywhere).

```BASH
Check Gravatar for xxx...
Check Gravatar for xxx...
Check Gravatar for xxx...
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 426, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 421, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.8/http/client.py", line 1347, in getresponse
    response.begin()
  File "/usr/lib/python3.8/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.8/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3/dist-packages/urllib3/contrib/pyopenssl.py", line 318, in recv_into
    raise SocketError(str(e))
OSError: (104, 'ECONNRESET')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 724, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 403, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/lib/python3/dist-packages/six.py", line 702, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 426, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 421, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.8/http/client.py", line 1347, in getresponse
    response.begin()
  File "/usr/lib/python3.8/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.8/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3/dist-packages/urllib3/contrib/pyopenssl.py", line 318, in recv_into
    raise SocketError(str(e))
urllib3.exceptions.ProtocolError: ('Connection aborted.', OSError("(104, 'ECONNRESET')"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hyiltiz/.local/bin/gitfaces", line 8, in <module>
    sys.exit(main())
  File "/home/hyiltiz/.local/lib/python3.8/site-packages/gitfaces/cli.py", line 18, in main
    gitfaces.fetch(args.repo, args.outdir)
  File "/home/hyiltiz/.local/lib/python3.8/site-packages/gitfaces/main.py", line 24, in fetch
    _fetch_gravatar(names_emails, out_dir)
  File "/home/hyiltiz/.local/lib/python3.8/site-packages/gitfaces/main.py", line 83, in _fetch_gravatar
    r = requests.get(url, params=params)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', OSError("(104, 'ECONNRESET')"))

```

**Comment by nschloe** [comment]
Looks like a network problem on your end.

**Comment by hyiltiz** [comment]
But the network has been stable throughout... In the exception that some connections got reset due to some IO state, maybe re-make those requests after a short timeout a few times until finally giving up?

**Comment by nschloe** [comment]
I don't know. I cannot reproduce the issue and no one else has had it yet, that's why I'm assuming it's your connection. Perhaps a firewall that filters certain packages? In any case, if you feel that the requests part could be improved, feel free to PR.

**Comment by hyiltiz** [comment]
Thanks! I don't think I'll debug this, but if it is annoying enough I might dig into it and come back with something.
